name: BattleZone
gym_backend: atari100k
gym_kwargs:
  seed: ${trainer.seed}
  terminal_on_life_loss: false
  noop_max: 30
  frame_skip: 4
  stack_size: 4

transforms:
  - _target_: torchrl.envs.RewardSum
  - _target_: torchrl.envs.StepCounter
    max_steps: 27000
